// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1
TEST_CASE("Ex1", "[example]")
{
	const int N = 10;
	int array[N] = {25, 10, 15, 30, 35, 40, 45, 55, 20, 50};

	bubbleSort(array, N);
	REQUIRE(array[0] == 10);
	REQUIRE(array[1] == 15);
	REQUIRE(array[2] == 20);
	REQUIRE(array[3] == 25);
	REQUIRE(array[4] == 30);
	REQUIRE(array[5] == 35);
	REQUIRE(array[6] == 40);
	REQUIRE(array[7] == 45);
	REQUIRE(array[8] == 50);
	REQUIRE(array[9] == 55);
}

// tests for exercise 2
TEST_CASE("Ex2", "[example]")
{
	const int N = 5;
	int array[N] = {5, 4, 3, 2, 1};

	bubbleSort(array, N);
	REQUIRE(array[0] == 1);
	REQUIRE(array[1] == 2);
	REQUIRE(array[2] == 3);
	REQUIRE(array[3] == 4);
	REQUIRE(array[4] == 5);
}